// eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNxdFFwY1ZZN0RlRXhOamJBV095cCJ9.eyJpc3MiOiJodHRwczovL2Rldi12ZHQ5enozcS51cy5hdXRoMC5jb20vIiwic3ViIjoiR1E0SkJWWFJqbEZLeFJRNHV4NE8zVlNlYUhYQW9UcmJAY2xpZW50cyIsImF1ZCI6ImRlbW9hcGkucmViZWxvZmJhdmFyaWEuZGUiLCJpYXQiOjE2MzE1NDc3NTcsImV4cCI6MTYzMTYzNDE1NywiYXpwIjoiR1E0SkJWWFJqbEZLeFJRNHV4NE8zVlNlYUhYQW9UcmIiLCJzY29wZSI6InJlYWQ6c2FtcGxlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwicGVybWlzc2lvbnMiOlsicmVhZDpzYW1wbGUiXX0.SQu18bNOdYUJOY96KWGBaOw71GQ9a8KyEchbxMPyzoJkjBjXiz3k_U9K-9BqhAkycKyB7trobKLZHXk8tWD9HA2AkFixEeQ8-ZEzfOKGTOZqfWzIcavACZql4i3CqVDMjyn-R8lD9LfG1NFDQhkv1vJjZEe6c5QQTOG4Pro5aziEEH0PNjGZzirdmnC0slIoKW-PrYP-qM6pL8RvseMGikvHhP5u7vXuv9EtUMDYm1eBcU4kxbkFi7fnwaYU7gxQ-pgN8vemJLyxSbqkrQ9hfB7AY5EM5adyWPzH1FVSAy98E-mwsOdLLYz-vljEg6MhmEv_BUJZioo02jjvm-J8Rg
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNxdFFwY1ZZN0RlRXhOamJBV095cCJ9.eyJpc3MiOiJodHRwczovL2Rldi12ZHQ5enozcS51cy5hdXRoMC5jb20vIiwic3ViIjoiT0VQcDdmazdSa0s4V1ozVlA1N2RPVWVqNnpSdHZYMHpAY2xpZW50cyIsImF1ZCI6ImRlbW9hcGkucmViZWxvZmJhdmFyaWEuZGUiLCJpYXQiOjE2NTcxODIxMzgsImV4cCI6MTY1NzI2ODUzOCwiYXpwIjoiT0VQcDdmazdSa0s4V1ozVlA1N2RPVWVqNnpSdHZYMHoiLCJzY29wZSI6InJlYWQ6c2FtcGxlIHdyaXRlOnNhbXBsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbInJlYWQ6c2FtcGxlIiwid3JpdGU6c2FtcGxlIl19.X7zGIla8UsP8soBNMpBUmI-Z1XREy6XLl1bGU0xVK2G7NPpoMgc8ExTN7ToVRqV_TT47TVYEGsyb7aOKoIe_ns01osD4_1vSNayJjP-ftMnb4qi5B5rPfDimQZ1XZW2e2MfM07H9YsDudfWILa-Ir9L-BP-w2RO2a7WdIx_JYWB_o38qWdwcpTatruegVQOuBXtEXoC7DtC5L3o8A4MP6QWWE_nGwry7jNvaL8h0MYJO-wMWY5vwJr-Duvvs-ucCR3HXt38scX6krRgSlsvXh0A4Q_BS7k086-hua90f7X0mhQGzfUpXEYrdoFSR2RFxgfzgi082povDyX6fQAyuCw

GET http://localhost:8080/redis/coasters
Authorization: Bearer {{token}}

####
GET http://localhost:8080/coasters/id578
Authorization: Bearer {{token}}

###
POST http://localhost:8080/redis/coasters
Authorization: Bearer {{token}}

{
  "name": "Coaster 11",
  "manufacture": "Manufacture 11",
  "id": "id11",
  "height": 500
}

###
GET http://localhost:8080/redis/extern
Authorization: Bearer {{token}}

###
DELETE http://localhost:8080/redis/coasters/id11
Authorization: Bearer {{token}}


###
GET http://localhost:8080/coasters
Authorization: Bearer {{token}}

###
POST http://localhost:8080/coasters
Authorization: Bearer {{token}}

{
  "name": "Coaster 7",
  "manufacture": "Manufacture 5",
  "id": "id5",
  "height": 323
}

###
GET http://localhost:8080/coasters/id852
Authorization: Bearer {{token}}

###
GET http://localhost:8080


####
GET http://localhost:8080/db/coasters

####
GET http://localhost:8080/db/coasters/id1

###
POST http://localhost:8080/db/coasters

{
  "name": "Coaster 7",
  "manufacture": "Manufacture 7",
  "id": "id7",
  "height": 323
}

###
DELETE http://localhost:8080/db/coasters/id7
