// eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNxdFFwY1ZZN0RlRXhOamJBV095cCJ9.eyJpc3MiOiJodHRwczovL2Rldi12ZHQ5enozcS51cy5hdXRoMC5jb20vIiwic3ViIjoiR1E0SkJWWFJqbEZLeFJRNHV4NE8zVlNlYUhYQW9UcmJAY2xpZW50cyIsImF1ZCI6ImRlbW9hcGkucmViZWxvZmJhdmFyaWEuZGUiLCJpYXQiOjE2MzE1NDc3NTcsImV4cCI6MTYzMTYzNDE1NywiYXpwIjoiR1E0SkJWWFJqbEZLeFJRNHV4NE8zVlNlYUhYQW9UcmIiLCJzY29wZSI6InJlYWQ6c2FtcGxlIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwicGVybWlzc2lvbnMiOlsicmVhZDpzYW1wbGUiXX0.SQu18bNOdYUJOY96KWGBaOw71GQ9a8KyEchbxMPyzoJkjBjXiz3k_U9K-9BqhAkycKyB7trobKLZHXk8tWD9HA2AkFixEeQ8-ZEzfOKGTOZqfWzIcavACZql4i3CqVDMjyn-R8lD9LfG1NFDQhkv1vJjZEe6c5QQTOG4Pro5aziEEH0PNjGZzirdmnC0slIoKW-PrYP-qM6pL8RvseMGikvHhP5u7vXuv9EtUMDYm1eBcU4kxbkFi7fnwaYU7gxQ-pgN8vemJLyxSbqkrQ9hfB7AY5EM5adyWPzH1FVSAy98E-mwsOdLLYz-vljEg6MhmEv_BUJZioo02jjvm-J8Rg
@token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjNxdFFwY1ZZN0RlRXhOamJBV095cCJ9.eyJpc3MiOiJodHRwczovL2Rldi12ZHQ5enozcS51cy5hdXRoMC5jb20vIiwic3ViIjoiT0VQcDdmazdSa0s4V1ozVlA1N2RPVWVqNnpSdHZYMHpAY2xpZW50cyIsImF1ZCI6ImRlbW9hcGkucmViZWxvZmJhdmFyaWEuZGUiLCJpYXQiOjE2MzI5MjQ2MDAsImV4cCI6MTYzMzAxMTAwMCwiYXpwIjoiT0VQcDdmazdSa0s4V1ozVlA1N2RPVWVqNnpSdHZYMHoiLCJzY29wZSI6InJlYWQ6c2FtcGxlIHdyaXRlOnNhbXBsZSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbInJlYWQ6c2FtcGxlIiwid3JpdGU6c2FtcGxlIl19.GFNS5bEqGK_fNpX7d7edC7a5DbyPal6kHKR-_9xO-O8TSYH_BCHS1Jw2GI6MefFyR0C6DzCzlHTVgfLrEB8b-YlDBIep5HLk1TGSfrn-8gScZxvk5wdoGCTprjHiApD09LNWjnjYk2x0PCuEUCz8szWmAwxJP4HnjeOZujtqtcc_VbpRprCDdLzQjGMgefPnDMjzo1ncTgudOzqerRaiHIWvrbQdf-ASJDjcYC6oHx8DLnFhlp0ma1bRwwxEq7qfbASopbJiclyS53RpIS-AlQiypTGbd8MCoI67JY5i4gPXjRDiUXKiDVMecTCtt2X6Nks6TPYS8UaKf9vJ4i4KiQ

GET http://localhost:8080/redis/coasters
Authorization: Bearer {{token}}


####
GET http://localhost:8080/redis/coasters/idw1
Authorization: Bearer {{token}}

###
POST http://localhost:8080/redis/coasters
Authorization: Bearer {{token}}

{
  "name": "Coaster 11",
  "manufacture": "Manufacture 11",
  "id": "id11",
  "height": 500
}

###
GET http://localhost:8080/redis/extern
Authorization: Bearer {{token}}

###
DELETE http://localhost:8080/redis/coasters/id1
Authorization: Bearer {{token}}


###
GET http://localhost:8080/coasters

###
POST http://localhost:8080/coasters

{
  "name": "Coaster 7",
  "manufacture": "Manufacture 5",
  "id": "id5",
  "height": 323
}

###
GET http://localhost:8080/coasters/id1

###
GET http://localhost:8080
