FROM golang:1.18-alpine3.16 as build
# checkov:skip=CKV_DOCKER_2
ARG ldflags

WORKDIR /app

COPY  . /app

RUN go mod download

RUN go build -ldflags "${ldflags}" -o /server ./src/kom.com/server/rest/echo/server_http.go 


## deploy -- hier Zielimage möglichst klein und sicher
FROM alpine:3.16

WORKDIR /

COPY --from=build /server /server

EXPOSE 8080

USER 12345:12345

ENTRYPOINT ["/server"]
