// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Coaster struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Manufacture *string `json:"manufacture"`
	Height      *int    `json:"height"`
}

type NewCoaster struct {
	Name        string  `json:"name"`
	Manufacture *string `json:"manufacture"`
	Height      *int    `json:"height"`
}
